### ISSUE TITLE
4.12+domains fails to compile async and CompCert with many gc-related errors

### ISSUE THREAD

**Issue by ewanmellor** [ocamllabs/ocaml-multicore#568]
Building CompCert with 4.12+domains fails with many errors related to the gc interface.  One example is below, but there are lots.

Building async with 4.12+domains fails with a different collection of errors, but they also are related to the gc interface.

Compiler: [71258842](https://github.com/ocaml-multicore/ocaml-multicore/commit/71258842a9f97393f62dd5e3cb0074c19958df69) (current HEAD of 4.12+domains branch).

CompCert full build log: https://multicore.ci.ocamllabs.io:8100/job/2021-06-08/043305-ci-ocluster-build-78d78a
CompCert successful build with stock 4.12, for comparison: https://multicore.ci.ocamllabs.io:8100/job/2021-06-08/043533-ci-ocluster-build-5c25c7

Async full build log: https://multicore.ci.ocamllabs.io:8100/job/2021-06-08/043214-ci-ocluster-build-3fd281
(I do not have a successful build of async with stock 4.12, due to other failures.)

To reproduce (CompCert):

```
git clone --recursive "https://github.com/ocaml-multicore/ocaml-multicore" -b "4.12+domains" && cd "ocaml-multicore" && git reset --hard 71258842
cat > Dockerfile <<'END-OF-DOCKERFILE'
FROM ocaml/opam@sha256:ed8f423a5568e86d46fa0c1895796d450b70fadd42f961afae74334c1a60a693
# Variant: debian-10-4.12+domains
USER 1000:1000
# Update opam-repository
WORKDIR /home/opam/opam-repository
RUN (git cat-file -e 161f03f0a11110be99f478b0ee1506b820e05f82 || git fetch origin master) && git reset -q --hard 161f03f0a11110be99f478b0ee1506b820e05f82 && git log --no-decorate -n1 --oneline && opam update -u
# Initialize project source
COPY --chown=1000:1000 . /src/
WORKDIR /src
# Create switch for compiler (compiler-71258842)
RUN opam switch create compiler-71258842 --empty && opam repository && opam pin add -k path --inplace-build ocaml-variants.4.12.0+multicore .
# Run build
RUN opam exec -- sudo apt-get install -y libgmp-dev
RUN opam exec -- opam install coq menhir
RUN opam exec -- ./configure x86_64-linux
RUN opam exec -- make
RUN opam exec -- make test

END-OF-DOCKERFILE
docker build .
```

To reproduce (async):
```
git clone --recursive "https://github.com/ocaml-multicore/ocaml-multicore" -b "4.12+domains" && cd "ocaml-multicore" && git reset --hard 71258842
cat > Dockerfile <<'END-OF-DOCKERFILE'
FROM ocaml/opam@sha256:ed8f423a5568e86d46fa0c1895796d450b70fadd42f961afae74334c1a60a693
# Variant: debian-10-4.12+domains
USER 1000:1000
# Update opam-repository
WORKDIR /home/opam/opam-repository
RUN (git cat-file -e 161f03f0a11110be99f478b0ee1506b820e05f82 || git fetch origin master) && git reset -q --hard 161f03f0a11110be99f478b0ee1506b820e05f82 && git log --no-decorate -n1 --oneline && opam update -u
# Initialize project source
COPY --chown=1000:1000 . /src/
WORKDIR /src
# Create switch for compiler (compiler-71258842)
RUN opam switch create compiler-71258842 --empty && opam repository && opam pin add -k path --inplace-build ocaml-variants.4.12.0+multicore .
# Run build
RUN opam exec -- opam install async

END-OF-DOCKERFILE
docker build .
```

Example failure (CompCert):

```
# OCAMLC    lib/pp_diff.mli
# In file included from /home/opam/.opam/compiler-71258842/lib/ocaml/caml/memory.h:26,
#                  from /home/opam/.opam/compiler-71258842/lib/ocaml/caml/roots.h:22,
#                  from coq_memory.c:17:
# coq_memory.c: In function 'init_coq_vm':
# coq_memory.c:115:56: error: 'Caml_black' undeclared (first use in this function); did you mean 'Caml_state'?
#      Hd_hp (accu_block) = Make_header (1, Abstract_tag, Caml_black);        \
#                                                         ^~~~~~~~~~
# /home/opam/.opam/compiler-71258842/lib/ocaml/caml/gc.h:26:24: note: in definition of macro 'Make_header'
#                      + (color)                                                 \
#                         ^~~~~
# coq_memory.c:115:56: note: each undeclared identifier is reported only once for each function it appears in
#      Hd_hp (accu_block) = Make_header (1, Abstract_tag, Caml_black);        \
#                                                         ^~~~~~~~~~
# /home/opam/.opam/compiler-71258842/lib/ocaml/caml/gc.h:26:24: note: in definition of macro 'Make_header'
#                      + (color)                                                 \
#                         ^~~~~
```

Example failure (async):
```
#          gcc src/gc_stubs.o (exit 1)
# (cd _build/default/src && /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -fPIC -D_FILE_OFFSET_BITS=64 -D_REENTRANT -O2 -fno-strict-aliasing -fwrapv -fPIC -D_LARGEFILE64_SOURCE -g -I /home/opam/.opam/compiler-71258842/lib/ocaml -I /home/opam/.opam/compiler-71258842/lib/base -I /home/opam/.opam/compiler-71258842/lib/base/base_internalhash_types -I /home/opam/.opam/compiler-71258842/lib/base/caml -I /home/opam/.opam/compiler-71258842/lib/base/md5 -I /home/opam/.opam/compiler-71258842/lib/base/shadow_stdlib -I /home/opam/.opam/compiler-71258842/lib/base_bigstring -I /home/opam/.opam/compiler-71258842/lib/base_quickcheck -I /home/opam/.opam/compiler-71258842/lib/bin_prot -I /home/opam/.opam/compiler-71258842/lib/bin_prot/shape -I /home/opam/.opam/compiler-71258842/lib/fieldslib -I /home/opam/.opam/compiler-71258842/lib/jane-street-headers -I /home/opam/.opam/compiler-71258842/lib/parsexp -I /home/opam/.opam/compiler-71258842/lib/ppx_assert/runtime-lib -I /home/opam/.opam/compiler-71258842/lib/ppx_bench/runtime-lib -I /home/opam/.opam/compiler-71258842/lib/ppx_compare/runtime-lib -I /home/opam/.opam/compiler-71258842/lib/ppx_enumerate/runtime-lib -I /home/opam/.opam/compiler-71258842/lib/ppx_expect/collector -I /home/opam/.opam/compiler-71258842/lib/ppx_expect/common -I /home/opam/.opam/compiler-71258842/lib/ppx_expect/config -I /home/opam/.opam/compiler-71258842/lib/ppx_expect/config_types -I /home/opam/.opam/compiler-71258842/lib/ppx_hash/runtime-lib -I /home/opam/.opam/compiler-71258842/lib/ppx_here/runtime-lib -I /home/opam/.opam/compiler-71258842/lib/ppx_inline_test/config -I /home/opam/.opam/compiler-71258842/lib/ppx_inline_test/runtime-lib -I /home/opam/.opam/compiler-71258842/lib/ppx_module_timer/runtime -I /home/opam/.opam/compiler-71258842/lib/ppx_sexp_conv/runtime-lib -I /home/opam/.opam/compiler-71258842/lib/sexplib -I /home/opam/.opam/compiler-71258842/lib/sexplib0 -I /home/opam/.opam/compiler-71258842/lib/splittable_random -I /home/opam/.opam/compiler-71258842/lib/stdio -I /home/opam/.opam/compiler-71258842/lib/time_now -I /home/opam/.opam/compiler-71258842/lib/typerep -I /home/opam/.opam/compiler-71258842/lib/variantslib -I ../base_for_tests/src -o gc_stubs.o -c gc_stubs.c)
# gc_stubs.c: In function 'minor_words':
# gc_stubs.c:7:20: error: 'caml_stat_minor_words' undeclared (first use in this function); did you mean 'caml_stat_alloc_noexc'?
#    return (intnat) (caml_stat_minor_words +
#                     ^~~~~~~~~~~~~~~~~~~~~
#                     caml_stat_alloc_noexc
```

**Comment by ctk21** [comment]
So I think the Async failures should be cleaned up by the merge of #590.
